const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = path.resolve(process.argv[2] || path.join(__dirname, '../..'));
const context = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(root, 'code/src/main/resources/static/assets/basket-ui.js'), 'utf8'), context);
const basket = context.BasketUI.createBasketModel();
const menu = {id:1, name:'Rice', price:0.10, isAvailable:true};
basket.add(menu, 2);basket.add(menu, 1);
assert.equal(basket.getItems()[0].quantity, 3);assert.equal(basket.total(), 0.3);
for (const quantity of [0, -1, 1.5, 100, NaN, Infinity]) assert.throws(() => basket.setQuantity(1, quantity), /1–99/);
basket.setQuantity(1, 99);assert.throws(() => basket.add(menu, 1), /1–99/);assert.equal(basket.getItems()[0].quantity, 99);
const copy = basket.getItems();copy[0].quantity=1;assert.equal(basket.getItems()[0].quantity, 99);
assert.throws(() => basket.add({...menu,id:2,isAvailable:false}, 1), /ปิดขาย/);
assert.throws(() => basket.add({...menu,id:2,price:-1}, 1), /ข้อมูล/);
basket.add({...menu,id:2,price:12.50}, 2);assert.equal(basket.total(), 34.9);
basket.remove(1);assert.equal(basket.total(), 25);basket.remove(2);assert.equal(basket.total(), 0);
assert.throws(() => basket.setQuantity(3, 1), /ไม่พบ/);
console.log('PASS: basket totals, typed quantities, boundaries, accumulated limit, removals, unavailable menus and snapshot isolation.');
