const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),ctx=vm.createContext({URL});vm.runInContext(fs.readFileSync(path.join(root,'code/src/main/resources/static/assets/qr.js'),'utf8'),ctx);
const node=()=>({value:'',handlers:{},disabled:true,hidden:true,addEventListener(n,f){this.handlers[n]=f;},removeEventListener(n){delete this.handlers[n];},removeAttribute(n){delete this[n];}});const make=()=>Object.fromEntries(['form','input','error','generate','print','image','link','card'].map(key=>[key,node()]));
async function run(){
 for(const value of ['http://example.com/','https://user:pass@example.com/','https://example.com/path','https://example.com/?token=x','https://example.com/#x','invalid'])assert.throws(()=>ctx.QrUI.validateUrl(value));assert.equal(ctx.QrUI.validateUrl('https://example.com'),'https://example.com/');
 let resolve,requests=0,printed=0,revoked=[];const e=make();e.input.value='https://example.com/';const qr=ctx.QrUI.createQr({elements:e,request:url=>{assert.match(url,/^\/staff\/qr.png\?url=/);requests++;return new Promise(r=>resolve=r);},createUrl:()=> 'blob:qr',revokeUrl:url=>revoked.push(url),decode:async()=>{},print:()=>printed++});
 const pending=qr.generate();await qr.generate();assert.equal(requests,1);assert.equal(e.generate.disabled,true);resolve({});await pending;assert.equal(e.print.disabled,false);assert.equal(e.card.hidden,false);assert.equal(e.link.textContent,'https://example.com/');e.print.handlers.click();assert.equal(printed,1);e.input.handlers.input();assert.equal(e.print.disabled,true);assert.deepEqual(revoked,['blob:qr']);qr.stop();
 const late=make();late.input.value='https://example.com/';const stopped=ctx.QrUI.createQr({elements:late,request:()=>new Promise(r=>resolve=r),createUrl:()=>assert.fail('must ignore disposed response'),revokeUrl:()=>{},decode:async()=>{}});const load=stopped.generate();stopped.stop();resolve({});await load;assert.equal(late.card.hidden,true);
 const denied=make();denied.input.value='https://example.com/';const failing=ctx.QrUI.createQr({elements:denied,request:async()=>{throw Error('staff access unavailable');}});await failing.generate();assert.equal(denied.error.textContent,'staff access unavailable');assert.equal(denied.print.disabled,true);failing.stop();
 console.log('PASS: QR URL limits, duplicate request guard, preview readiness, print, URL revocation, unavailable API and disposed response.');
}
run().catch(error=>{console.error(error);process.exitCode=1;});
