const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),ctx=vm.createContext({FormData,Blob});
for(const name of ['menu-ui','staff-menu-ui'])vm.runInContext(fs.readFileSync(path.join(root,`code/src/main/resources/static/assets/${name}.js`),'utf8'),ctx);
const node=()=>({value:'',textContent:'',disabled:true,hidden:true,handlers:{},addEventListener(n,f){this.handlers[n]=f;},removeEventListener(n){delete this.handlers[n];},querySelectorAll(){return [];},contains(){return true;},removeAttribute(n){delete this[n];},showModal(){this.open=true;},close(){this.open=false;this.handlers.close?.();}});
function make(){const result=Object.fromEntries(['form','dialog','file','preview','newMenu','deleteMenu','title','formError','error','grid','prev','next','page','close'].map(key=>[key,node()]));result.file.files=[];result.form.elements=Object.fromEntries(['id','name','category','price','prepTimeMinutes','isAvailable'].map(key=>[key,node()]));result.form.reportValidity=()=>true;result.form.reset=()=>{for(const field of Object.values(result.form.elements))field.value='';result.form.elements.isAvailable.checked=true;};return result;}
const menu={id:4,name:'<Rice>',category:'FOOD',price:10,prepTimeMinutes:5,isAvailable:false,imageUrl:'/image?v=1'};
function fill(e){const f=e.form.elements;f.name.value=' Rice ';f.category.value=' FOOD ';f.price.value='10.25';f.prepTimeMinutes.value='5';f.isAvailable.checked=true;}
async function run(){
 const {createEditor,validateFile,requestBody,multipart}=ctx.StaffMenuUI;
 for(const file of [{type:'image/svg+xml',size:2},{type:'image/png',size:0},{type:'image/png',size:2097153}])assert.throws(()=>validateFile(file));
 const form=make();fill(form);assert.equal(requestBody(form.form.elements).name,'Rice');form.form.elements.price.value='1.001';assert.throws(()=>requestBody(form.form.elements));form.form.elements.price.value='10';form.form.elements.prepTimeMinutes.value='241';assert.throws(()=>requestBody(form.form.elements));
 const upload=multipart({name:'Rice'},new Blob(['image'],{type:'image/png'}));assert.equal(upload.get('menu').type,'application/json');assert.equal(upload.get('file').type,'image/png');
 const e=make();let requests=[],release,revoked=[],allow=false;
 const editor=createEditor({elements:e,renderer:m=>m.name,photo:m=>m.imageUrl,createUrl:()=> 'blob:preview',revokeUrl:url=>revoked.push(url),confirmDelete:()=>allow,makeMultipart:(body,file)=>({body,file}),request:async(url,opts)=>{requests.push([url,opts]);if(opts)return new Promise(resolve=>release=resolve);return {content:[menu],totalPages:2};}});
 await editor.load();assert.match(requests[0][0],/includeUnavailable=true/);assert.equal(e.newMenu.disabled,false);editor.edit(menu);assert.equal(e.form.elements.id.value,'4');assert.equal(e.form.elements.isAvailable.checked,false);assert.equal(e.preview.src,'/image?v=1');
 e.file.files=[{type:'image/png',size:20}];editor.changeFile();assert.equal(e.preview.src,'blob:preview');e.file.files=[{type:'text/plain',size:20}];editor.changeFile();assert.deepEqual(revoked,['blob:preview']);assert.equal(e.preview.src,'/image?v=1');assert.ok(e.formError.textContent);
 e.file.files=[];fill(e);const save=editor.save();await editor.save();assert.equal(requests.length,2);assert.equal(requests[1][0],'/api/v1/menu-items/4');assert.equal(requests[1][1].method,'PUT');assert.equal(JSON.parse(requests[1][1].body).name,'Rice');assert.equal(e.newMenu.disabled,true);release(menu);await save;assert.equal(e.dialog.open,false);
 editor.edit(null);fill(e);e.file.files=[{type:'image/png',size:2}];const created=editor.save();assert.equal(requests[3][0],'/api/v1/menu-items/with-image');assert.equal(requests[3][1].method,'POST');assert.equal(requests[3][1].body.file,e.file.files[0]);release(menu);await created;
 editor.edit(menu);await editor.remove();assert.equal(requests.length,5);allow=true;const deleted=editor.remove();assert.equal(requests[5][0],'/api/v1/menu-items/4');assert.equal(requests[5][1].method,'DELETE');release(null);await deleted;editor.stop();
 const error=make();const denied=createEditor({elements:error,renderer:()=>'',photo:()=>'',request:async(url,opts)=>{if(opts)throw Error('close sales instead of deleting');return {content:[menu],totalPages:1};},confirmDelete:()=>true});await denied.load();denied.edit(menu);await denied.remove();assert.equal(error.formError.textContent,'close sales instead of deleting');assert.equal(error.dialog.open,true);denied.stop();
 const late=make();let resolve;const stopped=createEditor({elements:late,renderer:()=>assert.fail('late rendering'),photo:()=>'',request:()=>new Promise(r=>resolve=r)});const loading=stopped.load();stopped.stop();resolve({content:[menu],totalPages:1});await loading;assert.equal(late.grid.innerHTML,undefined);
 const escaped=ctx.MenuUI.createMenuRenderer({escapeHtml:s=>String(s??'').replaceAll('<','&lt;').replaceAll('>','&gt;'),money:String})(menu,true,true);assert.match(escaped,/&lt;Rice&gt;/);assert.match(escaped,/data-edit="4"/);
 console.log('PASS: staff menu validation, previews/revocation, JSON/multipart create/update, duplicate guard, delete confirmation/history error, escaped cards and disposed responses.');
}
run().catch(error=>{console.error(error);process.exitCode=1;});
